### ISSUE TITLE
Ayahs: add 'user-select: none'

### ISSUE THREAD

**Issue by mustafa0x** [quran/quran.com-frontend#949]
The user's first assumption is that the text is copyable, while that's not the case.

In addition to 'user-select: none' you can place the actual arabic text behind the special characters and make it transparent, so they'll select that instead.

**Comment by mmahalwy** [comment]
@mustafa0x this is a really good idea actually. So you're suggesting `user-select: none` on the glyphs but still have the text rendered as transparent in the background?

**Comment by mustafa0x** [comment]
Yeah, and the results aren't bad.

For longer ayahs you want to make sure the background text wraps similar to the ayah font.

Here's CSS I used to do (roughly) this:

```css
.mushaf-chars {
  user-select: none;
}

.uthmani {
  position: absolute;
  right: 0;
  top: 1.5rem;
  color: transparent;
}
```
